name: Test Trivy

on:
  workflow_dispatch:
    
permissions:
      security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'python:3.4-alpine'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'